# Generated by Django 4.1.7 on 2023-07-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0003_braininstancemodel_delete_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitBrainInstanceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=350)),
                ("brain_id", models.CharField(max_length=350)),
                ("generation_num", models.CharField(max_length=350)),
                ("hidden_weights", models.CharField(max_length=350)),
                ("output_weights", models.CharField(max_length=350)),
                ("fitness", models.CharField(max_length=350)),
                ("traversed_path", models.CharField(max_length=350)),
                ("fitness_by_step", models.CharField(max_length=350)),
            ],
        ),
        migrations.RenameModel(
            old_name="BrainInstanceModel",
            new_name="AllBrainInstanceModel",
        ),
    ]
