# Generated by Django 4.1.7 on 2023-07-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0004_fitbraininstancemodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allbraininstancemodel",
            name="hidden_weights",
            field=models.BinaryField(),
        ),
    ]
