# Generated by Django 4.1.7 on 2023-07-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0005_alter_allbraininstancemodel_hidden_weights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitbraininstancemodel",
            name="hidden_weights",
            field=models.BinaryField(),
        ),
    ]
