# Generated by Django 4.1.7 on 2023-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0006_alter_fitbraininstancemodel_hidden_weights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitbraininstancemodel",
            name="fitness_by_step",
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name="fitbraininstancemodel",
            name="output_weights",
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name="fitbraininstancemodel",
            name="traversed_path",
            field=models.BinaryField(),
        ),
    ]
