# Generated by Django 4.1.7 on 2023-07-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0007_alter_fitbraininstancemodel_fitness_by_step_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainedBrainInstanceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=350)),
                ("brain_type", models.CharField(default="trained", max_length=100)),
                ("brain_id", models.CharField(max_length=350)),
                ("generation_num", models.CharField(max_length=350)),
                ("fitness", models.CharField(max_length=350)),
                ("hidden_weights", models.BinaryField()),
                ("output_weights", models.BinaryField()),
                ("traversed_path", models.BinaryField()),
                ("fitness_by_step", models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name="allbraininstancemodel",
            name="brain_type",
            field=models.CharField(default="general", max_length=100),
        ),
        migrations.AddField(
            model_name="fitbraininstancemodel",
            name="brain_type",
            field=models.CharField(default="fit", max_length=100),
        ),
    ]
