# Generated by Django 4.1.7 on 2023-07-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0009_alter_trainedbraininstancemodel_fitness_by_step_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitbraininstancemodel",
            name="fitness_by_step",
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name="fitbraininstancemodel",
            name="traversed_path",
            field=models.CharField(max_length=350),
        ),
    ]
