# Generated by Django 4.1.7 on 2023-07-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0010_alter_fitbraininstancemodel_fitness_by_step_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitbraininstancemodel",
            name="title",
        ),
    ]
