# Generated by Django 4.1.7 on 2023-07-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0011_remove_fitbraininstancemodel_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allbraininstancemodel",
            name="title",
        ),
        migrations.RemoveField(
            model_name="trainedbraininstancemodel",
            name="title",
        ),
    ]
