# Generated by Django 4.1.7 on 2023-08-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0012_remove_allbraininstancemodel_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allbraininstancemodel",
            name="svg_path",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="fitbraininstancemodel",
            name="svg_path",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="trainedbraininstancemodel",
            name="svg_path",
            field=models.CharField(default="", max_length=350),
        ),
    ]
