# Generated by Django 4.1.7 on 2023-08-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0013_allbraininstancemodel_svg_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allbraininstancemodel",
            name="svg_end",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="allbraininstancemodel",
            name="svg_start",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="fitbraininstancemodel",
            name="svg_end",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="fitbraininstancemodel",
            name="svg_start",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="trainedbraininstancemodel",
            name="svg_end",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="trainedbraininstancemodel",
            name="svg_start",
            field=models.CharField(default="", max_length=350),
        ),
    ]
