# Generated by Django 4.1.7 on 2023-07-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="holder",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
